<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title> My GitHub Page </title>
</head>
<body>
  <h1>Welcome to My GitHub Page</h1>
  <p>This page was created for Assignment 2 using GitHub Pages.</p>

  <h2>About Me</h2>
  <table border="1" cellpadding="6" cellspacing="0">
    <thead>
      <tr>
        <th>Name</th>
        <th>Introduction</th>
        <th>Hobbies</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>Ethan Lilley</strong></td>
        <td>Hello, I am a junior in the BS Cyber program. I enjoy coding Python and R.</td>
        <td>Programming, making websites</td>
      </tr>
    </tbody>
  </table>
</body>
</html>
